### ISSUE TITLE
Help with running

### ISSUE THREAD

**Issue by Fabrimat** [Wardenfar/mc-osm-world-gen#5]
Hello, could you please provide more infos about how to run the software? Some examples would be much appreciated.

**Comment by Wardenfar** [comment]
Hello,
You first need a pbf file from OpenStreetMap. ( you can google it )
Then you can follow the steps in the README.
This is a command line app with two arguments : the path to the pbf file and the zoom (like in a map viewer). 
The pbf is a format that contains all the data from OpenStreetMap.

**Comment by Fabrimat** [comment]
I tried loading this one https://download.geofabrik.de/europe/italy/sud.html and after a couple of seconds it stops without doing anything other than filling up the RAM (I have 8 GB).
Command: `cargo run --release -- -p ./sud-latest.osm.pbf`
Output:
```
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/osm-world-gen -p ./sud-latest.osm.pbf`
Point { x: 17626069.636073243, y: 11963551.490457766 }
Point { x: 18951375.55192946, y: 12355543.600937886 }
start
```
And it exits after less than a minute.

**Comment by Wardenfar** [comment]
Yes it's way too large.
You can try to cut for a city. (Try small first then bigger if it works)
With this tool [osmconvert](https://wiki.openstreetmap.org/wiki/Osmconvert)

Example from the link :
```bash
osmconvert germany.pbf -b=10.5,49,11.5,50 -o=small.pbf
```
Tell me if it you have a working minecraft world at the end, and I will update the README

**Comment by Fabrimat** [comment]
Yes, it worked! Thank you very much.
I had a couple of missing regions but not a big problem.
