### ISSUE TITLE
help

### ISSUE THREAD

**Issue by akicatt** [Wardenfar/mc-osm-world-gen#6]
C:\Users\mark\Desktop\New folder (2)\mc-osm-world-gen\target\release>osm-world-gen.exe --pbf map.pbf
Point { x: 22003319.911801744, y: 10360519.263915043 }
Point { x: 22004436.46348857, y: 10360817.310016915 }
start
[00:00:00] (5689/s) #################################-------    2496/3072    [ETA 00:00:00]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\main.rs:240:56
[00:00:00] (5833/s) #######################################-    2976/3072    [ETA 00:00:00]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\main.rs:240:56thread '
[00:00:00] (5864/s) ########################################    3072/3072    [ETA 00:00:00]

**Comment by Wardenfar** [comment]
The program require the folder **./world/region** in your current directory.

Cd into the git root folder
Use this command:
cargo run --release -- --pbf map.pbf
(The world folder is already cloned with the git)

**Comment by akicatt** [comment]
thanks for the help!
